experiment:
  name: cnn_experiment

data:
  root: D:/open_datasets/Mars/mars_gait
  index_csv: inputs/sequences_mars_split.csv
  image_size: [256, 128]
  sequence_len: 25
  num_workers: 4

model:
  backbone: resnet50
  pretrained: true
  embed_dim: 512
  dropout: 0.1

train:
  epochs: 30
  batch:
    P: 3
    K: 3
  optimizer:
    lr: 0.0001
    weight_decay: 0.05

loss:
  ce:
    label_smoothing: 0.1
    weight: 1.0
  triplet:
    margin: 0.3
    weight: 1.0
